import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Contact from "./components/common/Contact";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased text-[14px]`}>
        <Contact />
        {children}
      </body>
    </html>
  );
}
